"""agent task_type for model routing

Revision ID: 1705b94c4bbc
Revises: f302f383b1a3
Create Date: 2026-05-27 08:23:00.192704
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1705b94c4bbc'
down_revision: Union[str, None] = 'f302f383b1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('task_type', sa.String(), server_default=sa.text("'auto'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'task_type')
    # ### end Alembic commands ###
