"""agent soul_md + persona

Revision ID: f302f383b1a3
Revises: f2f124aedf16
Create Date: 2026-05-27 06:24:31.326021
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f302f383b1a3'
down_revision: Union[str, None] = 'f2f124aedf16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('soul_md', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('persona', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'persona')
    op.drop_column('agents', 'soul_md')
    # ### end Alembic commands ###
